[package]
name = "libpillmom"
version = "0.1.0"
edition = "2021"

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(frb_expand)'] }

[lib]
name = "pillmom"
crate-type = ["cdylib", "staticlib"]

[dependencies]
# Flutter Rust Bridge
flutter_rust_bridge = "=2.11.1"

# Use libsql for both local SQLite and remote Turso connections
# This eliminates conflicts by using a single database library

tokio = { version = "1", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
chrono = { version = "0.4", features = ["serde"] }
dotenv = "0.15"
once_cell = "1.19"
tracing = "0.1"
tracing-subscriber = "0.3"
anyhow = "1.0"
async-trait = "0.1"

# libsql for Turso connection and embedded replicas
# Testing if v0.9 resolves conflicts - enable replication for all platforms
libsql = { version = "0.9", default-features = false, features = ["remote", "tls", "replication"] }

[target.'cfg(target_os = "android")'.dependencies]
android_logger = "0.14"

[profile.release]
lto = true
opt-level = "z"
codegen-units = 1
strip = true
