name: libpillmom
description: A Flutter plugin for managing medications and reminders using Rust+SeaORM/Turso via Flutter Rust Bridge
version: 0.1.0
repository: https://github.com/127thousand/libpillmom.git

topics:
  - medications
  - reminders
  - flutter-rust-bridge
  - seaorm
  - turso

environment:
  sdk: ^3.0.0
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_rust_bridge: 2.11.1
  ffi: ^2.1.0
  path: ^1.8.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  test: ^1.24.0

flutter:
  plugin:
    platforms:
      android:
        package: co.127k.libpillmom
        pluginClass: LibPillmomPlugin
        ffiPlugin: true
      ios:
        pluginClass: LibPillmomPlugin
        ffiPlugin: true
      linux:
        pluginClass: LibPillmomPlugin
        ffiPlugin: true
      macos:
        pluginClass: LibPillmomPlugin
        ffiPlugin: true
      windows:
        pluginClass: LibPillmomPlugin
        ffiPlugin: true